### ISSUE TITLE
30 second time limit discards valid data

### ISSUE THREAD

**Issue by Aesop-Shaym** [philippotto/Piano-Trainer#3]
Given a user who takes longer than 30 seconds rather often, a substantial chunk of valid data is discarded.

e.g. I've been studying piano for <60 hours (~45-55) and these (because they're outside the normal introductory playing range etc.) take anywhere from 12-40 seconds

**Comment by philippotto** [comment]
I understand the problem. The threshold of 30 seconds was rather arbitrary, but I am not sure what the ideal solution would be.

What do you think about a simple pause button which "pauses the game"? I don't have a piano at hands at the moment. Maybe you have time to write a PR?

Otherwise, we could simply increasing the threshold to 60 seconds so that at least *you* can practise without any problems? This would be a quick'n'dirty-fix, of course.

**Comment by philippotto** [comment]
The new version has a start/stop button which solves this issue.
