### ISSUE TITLE
Allow selecting MIDI input device

### ISSUE THREAD

**Issue by liias** [philippotto/Piano-Trainer#4]
My OS has chosen the piano as 2nd MIDI input device next to some other one for whatever reason.

So allowing to select the MIDI input device would be nice.

**Comment by philippotto** [comment]
I'm very sorry that I didn't reply earlier. Somehow it slipped through the cracks. I saw your PR and the code looks very good. Unfortunately, I ported the codebase to es6 and react, which is why I can't apply the PR directly.

However, I committed something on the `multiple-devices` branch which should accomplish the same as your PR.

If you are still up for it, @liias, you can check out the branch and test it out. Since I don't have a midi device on hand at the moment (let alone multiple devices), I couldn't test it properly. That's why, I'd be very happy if you could test it.
