### ISSUE TITLE
Flat/Sharp notes

### ISSUE THREAD

**Issue by Finomnis** [philippotto/Piano-Trainer#6]
First of all, this is an awesome project and I hope that it is not abandoned yet.

I noticed that it helped me a lot, but I miss generation of flat/sharp notes.
Also, I would like an option to change the scale.

So I suggest to add:
- Possibility to change the base scale
- Generation of notes outside of the current scale (with lower probability)

**Comment by Finomnis** [comment]
Ok I realized from looking at the code that this option already exists. How do you switch it on?

**Comment by philippotto** [comment]
Hi @Finomnis! Thanks for your kind words and suggestions. Actually, I wanted to work on this project again in the next couple of days. In addition to flat/sharp notes and different scales, I also want to add training for rhythm. So, stay tuned!

It will probably take some time, though, since I want to move the project from backbone to react first. Unfortunately, I currently don't have a piano, so I cannot really test things. But maybe you could test some features if they are ready?

**Comment by Finomnis** [comment]
Yes, I do have a piano, and sure, I think I could test things for you.

**Comment by philippotto** [comment]
Hi Martin, as promised a worked a bit on a new version of the Piano-Trainer. Feel free to test it here:
http://philippotto.github.io/Piano-Trainer/es6/

I'd be happy if you could tell me if everything works. The new version is written in ES6 with React instead of coffeescript and backbone. Additionally, it features a setting dialog which allows to adapt the number of notes per chord and whether one wants to have accidentals (flat/sharp notes). I'll lower  the probability of flats and sharps and also will add the possibility to have a different base scale, soon.

**Comment by Finomnis** [comment]
Hi!

Cool! Thanks for your work.

I do have a bug report right away, though.

In C-Major scale, which this currently is, it does generate e-sharp and 
b-sharp, which technically exist, but in a normal scale are represented 
by f and c.
I guess the same accounts for f-b and c-b.

Greetings,
Martin

**Comment by philippotto** [comment]
Good point! The note generation is very naive at the moment, but I will improve it in combination with the upcoming base scale support. Thanks for pointing that out!
